### PR TITLE
Create messages.json

### PR DESCRIPTION
**Pull request by cjavad**
Added danish translation. Handwritten.

### CODE REVIEW

**Comment by cjavad** [comment]
Sure thing.

**Comment by cjavad** [comment]
@bladegery Reverted the description fields to english.

**Comment by bladegery** [comment]
Thanks, merged it, will add you as a contributor.

**Comment by bladegery** [comment]
https://github.com/bladegery/csgo-trader-extension/blob/master/CONTRIBUTING.md

**Pull request merged**
